### ISSUE TITLE
总结下使用这个组件时自己的问题

### ISSUE THREAD

**Issue by pepsihuang** [raoooool/flomo-reminder#2]
1. fork仓库时，并不会立马执行，需要等到workflow里面设置的时间才会执行一次。所以对于想要验证的同学需要先修改workflow的schedule ， 比如我改为push一次就执行一次action。
2. 首次填写secret以为是把代码全部复制到value里面，原来并不是这样。而是必须要 key为：FLOMO_AUTHORIZATION 然后value填 Bearerxxxx 。
3. Bark的value不是网址 （https://api.day.app/PoJvxxxxxxxx/'），而是网址后的id（PoJvxxxxxxxx）。

**Comment by pepsihuang** [comment]
另外要善于使用action里的log，才能看出来是什么错误。

感谢raoooool 写的功能。

**Comment by raoooool** [comment]
感谢反馈！！
如果有什么功能建议也欢迎继续反馈或者PR，我会持续改进这个项目😄
